Update to socket.c as it was broken with undefined reference to Cfd_set when it was supposed to be the class CFDSET. Still need to work on the MakeFile some more.